language: go
sudo: false

go:
- 1.10

before_install:
- go get github.com/mattn/goveralls
- go get github.com/kardianos/govendor
- govendor sync

script:
- goveralls
- cd cmd/konturtransferbot && go build
